USE [master]
GO

/****** Object:  Database [Edutech]    Script Date: 29/10/2021 11:17:10 ******/
CREATE DATABASE [Edutech]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Edutech', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\Edutech.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Edutech_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\Edutech_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Edutech].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Edutech] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Edutech] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Edutech] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Edutech] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Edutech] SET ARITHABORT OFF 
GO

ALTER DATABASE [Edutech] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [Edutech] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Edutech] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Edutech] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Edutech] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Edutech] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Edutech] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Edutech] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Edutech] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Edutech] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Edutech] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Edutech] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Edutech] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Edutech] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Edutech] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Edutech] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Edutech] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Edutech] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Edutech] SET  MULTI_USER 
GO

ALTER DATABASE [Edutech] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Edutech] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Edutech] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Edutech] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Edutech] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Edutech] SET QUERY_STORE = OFF
GO

USE [Edutech]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [Edutech] SET  READ_WRITE 
GO

